// Generated by scripts/sync-default-profiles.mjs. Do not hand edit.
export const DEFAULT_PROFILE_CATALOG = [
  {
    "displayName": "只爱学习的二中学子",
    "avatarUrl": "profile:001",
    "asset": "ui/profiles/001/texture"
  },
  {
    "displayName": "如何科学养鸡.",
    "avatarUrl": "profile:002",
    "asset": "ui/profiles/002/texture"
  },
  {
    "displayName": "梦里梦外都是你",
    "avatarUrl": "profile:003",
    "asset": "ui/profiles/003/texture"
  },
  {
    "displayName": "💤",
    "avatarUrl": "profile:004",
    "asset": "ui/profiles/004/texture"
  },
  {
    "displayName": "★无名指的↔等待",
    "avatarUrl": "profile:005",
    "asset": "ui/profiles/005/texture"
  },
  {
    "displayName": "想你……",
    "avatarUrl": "profile:006",
    "asset": "ui/profiles/006/texture"
  },
  {
    "displayName": "月.泽^",
    "avatarUrl": "profile:007",
    "asset": "ui/profiles/007/texture"
  },
  {
    "displayName": "淡淡如水",
    "avatarUrl": "profile:008",
    "asset": "ui/profiles/008/texture"
  },
  {
    "displayName": "老",
    "avatarUrl": "profile:011",
    "asset": "ui/profiles/011/texture"
  },
  {
    "displayName": "e小S的",
    "avatarUrl": "profile:012",
    "asset": "ui/profiles/012/texture"
  },
  {
    "displayName": "4七",
    "avatarUrl": "profile:014",
    "asset": "ui/profiles/014/texture"
  },
  {
    "displayName": "山2",
    "avatarUrl": "profile:015",
    "asset": "ui/profiles/015/texture"
  },
  {
    "displayName": "小",
    "avatarUrl": "profile:016",
    "asset": "ui/profiles/016/texture"
  },
  {
    "displayName": "人这",
    "avatarUrl": "profile:017",
    "asset": "ui/profiles/017/texture"
  },
  {
    "displayName": "六 9九上o多",
    "avatarUrl": "profile:018",
    "asset": "ui/profiles/018/texture"
  },
  {
    "displayName": "心2",
    "avatarUrl": "profile:019",
    "asset": "ui/profiles/019/texture"
  },
  {
    "displayName": "风手和-",
    "avatarUrl": "profile:021",
    "asset": "ui/profiles/021/texture"
  },
  {
    "displayName": "小孤情-7",
    "avatarUrl": "profile:022",
    "asset": "ui/profiles/022/texture"
  },
  {
    "displayName": "回福",
    "avatarUrl": "profile:023",
    "asset": "ui/profiles/023/texture"
  },
  {
    "displayName": "n大丶",
    "avatarUrl": "profile:024",
    "asset": "ui/profiles/024/texture"
  },
  {
    "displayName": "城 人言你你我g乐装如多be飞号I清",
    "avatarUrl": "profile:025",
    "asset": "ui/profiles/025/texture"
  },
  {
    "displayName": "别加👑",
    "avatarUrl": "profile:026",
    "asset": "ui/profiles/026/texture"
  },
  {
    "displayName": "水叶福g电",
    "avatarUrl": "profile:027",
    "asset": "ui/profiles/027/texture"
  },
  {
    "displayName": "思 o春",
    "avatarUrl": "profile:028",
    "asset": "ui/profiles/028/texture"
  }
] as const
